# Generated by Django 4.1.3 on 2022-11-27 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itemName', models.TextField(max_length=50)),
                ('desription', models.TextField(null=True)),
                ('price', models.FloatField()),
                ('stock', models.IntegerField()),
            ],
        ),
    ]
