# Generated by Django 4.1.3 on 2022-11-27 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productpage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='itemImg',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
