# Generated by Django 4.1.3 on 2022-11-27 04:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productpage', '0002_item_itemimg'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='desription',
            new_name='category',
        ),
    ]
