# Generated by Django 4.1.3 on 2022-11-27 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('productpage', '0003_rename_desription_item_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='category',
        ),
    ]
