# Generated by Django 4.1.3 on 2022-11-27 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productpage', '0004_remove_item_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='itemCategory',
            field=models.CharField(choices=[('V', 'Vegetables'), ('F', 'Fruits'), ('K', 'Kitchen')], max_length=1, null=True),
        ),
    ]
