# Generated by Django 4.1.3 on 2022-11-27 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productpage', '0005_item_itemcategory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='id',
        ),
        migrations.AddField(
            model_name='item',
            name='itemID',
            field=models.IntegerField(default=20, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
