# Generated by Django 4.1.3 on 2022-11-27 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productpage', '0008_remove_item_id_item_itid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='itID',
        ),
        migrations.AddField(
            model_name='item',
            name='itemID',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
            preserve_default=False,
        ),
    ]
