# Generated by Django 4.1.3 on 2022-11-28 04:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('productpage', '0012_cart_remove_order_placed_cart_item'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='custName',
            new_name='FirstName',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='address',
        ),
        migrations.AddField(
            model_name='customer',
            name='LastName',
            field=models.TextField(default='S', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
